[metadata]
name = porthole
version = attr: porthole.version.version
description = GTK frontend to Portage
long_description = file: README
long_description_content_type = text/plain
author = Fredrik Arnerup, Daniel G. Taylor, Brian Dolbec, William F. Wheeler
author_email = dol-sen@users.sourceforge.net, farnerup@users.sourceforge.net, dgt84@users.sourceforge.net, tiredoldcoder@users.sourceforge.net
url = http://porthole.sourceforge.net
license = GPL-2.0-or-later
classifiers =
    Development Status :: 4 - Beta
    Environment :: X11 Applications :: GTK
    Intended Audience :: System Administrators
    License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)
    Operating System :: POSIX :: Linux
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.12
    Topic :: System :: Software Distribution

[options]
packages = find:
python_requires = >=3.12
scripts =
    scripts/porthole
include_package_data = False

[options.packages.find]
include =
    porthole*
exclude =
    porthole-old*

[options.data_files]
share/applications =
    porthole.desktop
share/pixmaps =
    porthole/pixmaps/porthole-icon.png
share/porthole =
    AUTHORS
    TRANSLATORS
    scripts/dopot.sh
    scripts/pocompile.sh
share/porthole/config =
    porthole/config/configuration.xml
share/porthole/glade =
    porthole/glade/about.glade
    porthole/glade/advemerge.glade
    porthole/glade/config.glade
    porthole/glade/main_window.glade
    porthole/glade/plugin_dialog.glade
    porthole/glade/porthole.glade
    porthole/glade/process_window.glade
    porthole/glade/run_dialog.glade
share/porthole/help =
    porthole/help/advemerge.html
    porthole/help/advemerge.png
    porthole/help/changelog.png
    porthole/help/custcmd.html
    porthole/help/custcmd.png
    porthole/help/customize.html
    porthole/help/dependencies.png
    porthole/help/depview.png
    porthole/help/ebuildtable_explained2.png
    porthole/help/index.html
    porthole/help/install.html
    porthole/help/installedfiles.png
    porthole/help/mainwindow.html
    porthole/help/mainwindow.png
    porthole/help/porthole.css
    porthole/help/queuetab.png
    porthole/help/search.html
    porthole/help/summarytab.png
    porthole/help/sync.html
    porthole/help/termrefs.html
    porthole/help/termwindow.html
    porthole/help/termwindow.png
    porthole/help/toc.html
    porthole/help/unmerge.html
    porthole/help/update.html
    porthole/help/upgradeables.png
    porthole/help/warningtab.png
share/porthole/i18n =
    porthole/i18n/messages.pot
    porthole/i18n/TRANSLATING
share/porthole/i18n/de/LC_MESSAGES =
    porthole/i18n/de/LC_MESSAGES/porthole.mo
share/porthole/i18n/fr/LC_MESSAGES =
    porthole/i18n/fr/LC_MESSAGES/porthole.mo
share/porthole/i18n/it/LC_MESSAGES =
    porthole/i18n/it/LC_MESSAGES/porthole.mo
share/porthole/i18n/pl/LC_MESSAGES =
    porthole/i18n/pl/LC_MESSAGES/porthole.mo
share/porthole/i18n/ru/LC_MESSAGES =
    porthole/i18n/ru/LC_MESSAGES/porthole.mo
share/porthole/i18n/tr/LC_MESSAGES =
    porthole/i18n/tr/LC_MESSAGES/porthole.mo
share/porthole/i18n/vi/LC_MESSAGES =
    porthole/i18n/vi/LC_MESSAGES/porthole.mo
share/porthole/pixmaps =
    porthole/pixmaps/porthole-about.png
    porthole/pixmaps/porthole-clock-20x20.png
    porthole/pixmaps/porthole-clock.png
    porthole/pixmaps/porthole-icon.png
    porthole/pixmaps/porthole.svg

[sdist]
formats = bztar
